### PR TITLE
Issue-163: Add delete and edit functionality for tables

### LINKED ISSUE #163: Table setting: Ability to edit Table name
**Current behavior**
User is unable to edit the Table name.

**To Reproduce**

1. Go to Data section
2. Click on an existing table
3. Click on 'Settings' button
4. On the left Settings panel see the table information

**Expected behavior**
User goes to the Tables Settings and is able to edit the Table name and Save it.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Kimaiyo077**
## What is the Purpose?
Add edit and delete functionality to settings drawer

## What was the approach?
- Add confirm delete modal
- Hook up actions to respective buttons

## Are there any concerns to addressed further before or after merging this PR?
None

## Mentions?
@ninetteadhikari 

## Issue(s) affected?
Close #163 #99

### CODE REVIEW

File: src/lang/en.js [hunk 1]
```diff
@@ -142,7 +142,9 @@ export default {
       exportTable: 'Export',
       tableName: 'Table name',
       ownerName: 'Owner',
-      source: 'Source'
+      source: 'Source',
+      delete: 'Are you sure you want to delete this table: {table}? This action cannot be undone.'
```
Comment (ninetteadhikari) [inline src/lang/en.js:146]: @Kimaiyo077 is it possible to make the table name `{table}` **bold**?

Comment (Kimaiyo077) [reply src/lang/en.js]: @ninetteadhikari I have been able to make the changes
